/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * The DB image ID if applicable (e.g., for ghost records).
 */
export type AuditIssueImageId = number | null;
