/**
 * Type definition for the found perceptual hash in an audit issue.
 * Represents the actual hash value calculated from the image file on disk.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type AuditIssueFoundPhash = string | null;
