/**
 * Type definition for the expected perceptual hash in an audit issue.
 * Represents the hash value the database expected for a given image.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type AuditIssueExpectedPhash = string | null;
