/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { AuditIssueDirectory } from './auditIssueDirectory';
import type { AuditIssueImageId } from './auditIssueImageId';
import type { AuditIssueSetId } from './auditIssueSetId';
import type { AuditIssueExpectedPhash } from './auditIssueExpectedPhash';
import type { AuditIssueFoundPhash } from './auditIssueFoundPhash';
import type { AuditIssueMatchIssueId } from './auditIssueMatchIssueId';
import type { AuditIssueSetTitle } from './auditIssueSetTitle';
import type { AuditIssueCreatorName } from './auditIssueCreatorName';

export interface AuditIssue {
  task_id: string;
  issue_type: string;
  path: string;
  directory?: AuditIssueDirectory;
  image_id?: AuditIssueImageId;
  set_id?: AuditIssueSetId;
  expected_phash?: AuditIssueExpectedPhash;
  found_phash?: AuditIssueFoundPhash;
  match_issue_id?: AuditIssueMatchIssueId;
  status?: string;
  id: number;
  created_at: string;
  set_title?: AuditIssueSetTitle;
  creator_name?: AuditIssueCreatorName;
}
