/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * ID of a related issue if they are paired (e.g., a moved file).
 */
export type AuditIssueMatchIssueId = number | null;
