/**
 * @file
 * Data model for a paginated list of audit issues.
 * Contains an array of issues along with total count and pagination metadata.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { AuditIssue } from './auditIssue';

export interface AuditIssuePage {
  items: AuditIssue[];
  total: number;
  skip: number;
  limit: number;
}
