/**
 * @file
 * Type definition for the set title in an audit issue.
 * Represents an optional string associated with the set involved in the issue.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type AuditIssueSetTitle = string | null;
