/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * The parent directory of the file, useful for grouping.
 */
export type AuditIssueDirectory = string | null;
