/**
 * Type definition for the directory path in an audit issue.
 * Represents an optional string indicating where the issue was found.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type AuditIssueDirectory = string | null;
