/**
 * Type definition for the match issue ID in an audit issue.
 * Represents an optional reference to another related issue.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type AuditIssueMatchIssueId = number | null;
