/**
 * @file
 * Type definition for the set ID in an audit issue.
 * Represents an optional numeric identifier for the set containing the image.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type AuditIssueSetId = number | null;
