/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface AuditFixAction {
  /** List of issue IDs to apply the fix to. */
  issue_ids: number[];
  /** The resolution action: 'purge', 'import', 'repair', 'delete_file', 'ignore'. */
  action: string;
}
