/**
 * @file
 * Data model for an audit start request payload.
 * Used to trigger a new library audit, with an option to enable deep scanning.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface AuditStartRequest {
  deep_scan?: boolean;
}
