/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * The expected perceptual hash if known.
 */
export type AuditIssueExpectedPhash = string | null;
