/**
 * @file
 * Data model for an audit fix action.
 * Defines the shape of the payload used when resolving
 * one or multiple audit issues simultaneously.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface AuditFixAction {
  issue_ids: number[];
  action: string;
}
