/**
 * @file
 * Type definition for the creator name in an audit issue.
 * Represents an optional string associated with the issue's image or set.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type AuditIssueCreatorName = string | null;
