/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * The actual perceptual hash calculated during the scan.
 */
export type AuditIssueFoundPhash = string | null;
