/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface AuditStartRequest {
  /** If true, recalculates file hashes to verify integrity rather than just checking existence. */
  deep_scan?: boolean;
}
