/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface AutoTagResponse {
  /** Unique UUID for the background auto-tagging task. */
  task_id: string;
  /** Current status of the task. */
  status: string;
}
