/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Summary statistics of the import operation.
 */
export type BatchImportResponseSummary = { [key: string]: unknown };
