/**
 * @file
 * Type definition for a batch import parsing template.
 * Represents a string format used to extract metadata from folder paths.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type BatchImportRequestParsingTemplate = string | null;
