/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Overall status of the batch import request.
 */
export type BatchImportResponseStatus = string | null;
