/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Background task ID if the import was queued asynchronously.
 */
export type BatchImportResponseTaskId = string | null;
