/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { BatchImportItem } from './batchImportItem';
import type { BatchImportResponseSummary } from './batchImportResponseSummary';

export interface BatchImportResponse {
  items: BatchImportItem[];
  summary?: BatchImportResponseSummary;
}
