/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SetBatchImport } from './setBatchImport';
import type { BatchImportRequestParsingTemplate } from './batchImportRequestParsingTemplate';

export interface BatchImportRequest {
  items?: SetBatchImport[];
  scan_auto_path?: boolean;
  dry_run?: boolean;
  parsing_template?: BatchImportRequestParsingTemplate;
  delete_source_default?: boolean;
}
