/**
 * Module defining the BatchImportResponseTaskId type.
 * This auto-generated Orval model represents the background task identifier
 * associated with a batch import operation.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type BatchImportResponseTaskId = string | null;
