/**
 * Data model for a single batch import item.
 * Represents an individual source directory mapped to a creator and set title.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { BatchImportItemError } from './batchImportItemError';

export interface BatchImportItem {
  source_path: string;
  creator_name: string;
  set_title: string;
  status?: string;
  error?: BatchImportItemError;
  isValid?: boolean;
}
