/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Regex template used to extract Creator and Set names from the directory structure (e.g., '[Creator] - [Set]').
 */
export type BatchImportRequestParsingTemplate = string | null;
