/**
 * Module defining the BatchImportResponseStatus type.
 * This model is auto-generated by Orval from the backend OpenAPI specification.
 * It represents the status string of a batch import response.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type BatchImportResponseStatus = string | null;
