/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { BatchImportItem } from './batchImportItem';
import type { BatchImportResponseSummary } from './batchImportResponseSummary';
import type { BatchImportResponseTaskId } from './batchImportResponseTaskId';
import type { BatchImportResponseStatus } from './batchImportResponseStatus';

export interface BatchImportResponse {
  /** Status of each imported item. */
  items: BatchImportItem[];
  /** Summary statistics of the import operation. */
  summary?: BatchImportResponseSummary;
  /** Background task ID if the import was queued asynchronously. */
  task_id?: BatchImportResponseTaskId;
  /** Overall status of the batch import request. */
  status?: BatchImportResponseStatus;
}
