/**
 * @file
 * Module defining the BatchImportResponseSummary type.
 * This auto-generated Orval model represents the summary statistics
 * returned as part of a batch import response.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type BatchImportResponseSummary = { [key: string]: unknown };
