/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type BulkOperationMode = typeof BulkOperationMode[keyof typeof BulkOperationMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BulkOperationMode = {
  replace: 'replace',
  append: 'append',
  remove: 'remove',
} as const;
