/**
 * @file
 * Module defining the BulkOperationMode type.
 * This model is auto-generated by Orval from the backend OpenAPI specification.
 * It is used for API communication regarding bulk operation modes.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type BulkOperationMode = typeof BulkOperationMode[keyof typeof BulkOperationMode];


 
export const BulkOperationMode = {
  replace: 'replace',
  append: 'append',
  remove: 'remove',
} as const;
