/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CharacterUpdateName } from './characterUpdateName';
import type { CharacterUpdateFranchiseId } from './characterUpdateFranchiseId';

export interface CharacterUpdate {
  /** The updated name of the character. */
  name?: CharacterUpdateName;
  /** The updated franchise ID. */
  franchise_id?: CharacterUpdateFranchiseId;
}
