/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * The updated franchise ID.
 */
export type CharacterUpdateFranchiseId = number | null;
