/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CharacterCreateFranchiseId } from './characterCreateFranchiseId';

export interface CharacterCreate {
  /** The name of the character. */
  name: string;
  /** The ID of the franchise this character belongs to. */
  franchise_id?: CharacterCreateFranchiseId;
}
