/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * The ID of the franchise this character belongs to.
 */
export type CharacterCreateFranchiseId = number | null;
