/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * The most common aspect ratio among this creator's images.
 */
export type CreatorStatsPrimaryAspectRatio = string | null;
