/**
 * Module defining the CreatorWithSetsStats type.
 * This model is auto-generated by Orval from the backend OpenAPI specification.
 * It encapsulates statistical data regarding a creator along with its sets.
 */
/**
 * Defines the API model for CreatorWithSetsStats.
 * Represents the creator statistics data structure used by the frontend.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CreatorStats } from './creatorStats';

export type CreatorWithSetsStats = CreatorStats | null;
