/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CreatorStats } from './creatorStats';

export type CreatorStatsProperty = CreatorStats | null;
