/**
 * @file
 * Module defining the CreatorCreate interface.
 * This model is auto-generated by Orval from the backend OpenAPI specification.
 * It represents the data payload for creating a new creator.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CreatorCreateType } from './creatorCreateType';
import type { CreatorCreateNotes } from './creatorCreateNotes';

export interface CreatorCreate {
  canonical_name: string;
  type?: CreatorCreateType;
  notes?: CreatorCreateNotes;
}
