/**
 * Module defining the CreatorStatsPreviewImageId type.
 * This model is auto-generated by Orval from the backend OpenAPI specification.
 * It represents the preview image identifier within creator statistics.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type CreatorStatsPreviewImageId = number | null;
