/**
 * Module defining the CreatorNotes type.
 * This model is auto-generated by Orval from the backend OpenAPI specification.
 * It represents the notes associated with a creator.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type CreatorNotes = string | null;
