/**
 * @file
 * Module defining the CreatorWithSetsNotes type.
 * This model is auto-generated by Orval from the backend OpenAPI specification.
 * It represents the notes associated with a creator that includes its sets.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type CreatorWithSetsNotes = string | null;
