/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * The primary, normalized name of the artist/creator.
 */
export type CreatorUpdateCanonicalName = string | null;
