/**
 * @file
 * Module defining the CreatorType enum or type.
 * This model is auto-generated by Orval from the backend OpenAPI specification.
 * It represents the type or category of a creator.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type CreatorType = string | null;
