/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CreatorWithSetsType } from './creatorWithSetsType';
import type { CreatorWithSetsNotes } from './creatorWithSetsNotes';
import type { Set } from './set';

export interface CreatorWithSets {
  canonical_name: string;
  type?: CreatorWithSetsType;
  notes?: CreatorWithSetsNotes;
  id: number;
  sets?: Set[];
}
