/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface CreatorMerge {
  /** List of duplicate creator IDs that will be merged into the target and then deleted. */
  source_ids: number[];
  /** The ID of the primary creator that will absorb the source creators. */
  target_id: number;
}
