/**
 * @file
 * Defines the API model for CreatorWithSetsType.
 * Represents the type information for a creator entity.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type CreatorWithSetsType = string | null;
