/**
 * @file
 * Module defining the CreatorStatsProperty type.
 * This model is auto-generated by Orval from the backend OpenAPI specification.
 * It represents a property key or value within creator statistics.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CreatorStats } from './creatorStats';

export type CreatorStatsProperty = CreatorStats | null;
