/**
 * @file
 * Module defining the CreatorUpdate interface.
 * This model is auto-generated by Orval from the backend OpenAPI specification.
 * It represents the data payload for updating an existing creator.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CreatorUpdateCanonicalName } from './creatorUpdateCanonicalName';
import type { CreatorUpdateType } from './creatorUpdateType';
import type { CreatorUpdateNotes } from './creatorUpdateNotes';

export interface CreatorUpdate {
  canonical_name?: CreatorUpdateCanonicalName;
  type?: CreatorUpdateType;
  notes?: CreatorUpdateNotes;
}
