/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CreatorWithSetsType } from './creatorWithSetsType';
import type { CreatorWithSetsNotes } from './creatorWithSetsNotes';
import type { CreatorWithSetsStats } from './creatorWithSetsStats';
import type { Set } from './set';

export interface CreatorWithSets {
  /** The primary, normalized name of the artist/creator. */
  canonical_name: string;
  /** Type of creator (e.g., 'photographer', 'illustrator', 'cosplayer'). */
  type?: CreatorWithSetsType;
  /** User-provided notes or biography for the creator. */
  notes?: CreatorWithSetsNotes;
  /** Unique database identifier for the creator. */
  id: number;
  /** Aggregated statistics for the creator's portfolio. */
  stats?: CreatorWithSetsStats;
  /** List of all sets belonging to this creator. */
  sets?: Set[];
}
