/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CreatorType } from './creatorType';
import type { CreatorNotes } from './creatorNotes';
import type { CreatorStatsProperty } from './creatorStatsProperty';

export interface Creator {
  canonical_name: string;
  type?: CreatorType;
  notes?: CreatorNotes;
  id: number;
  stats?: CreatorStatsProperty;
}
