/**
 * @file
 * Module defining the CreatorStatsPrimaryAspectRatio type.
 * This model is auto-generated by Orval from the backend OpenAPI specification.
 * It represents the primary aspect ratio within creator statistics.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type CreatorStatsPrimaryAspectRatio = string | null;
