/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { Creator } from './creator';

export interface CreatorPage {
  items: Creator[];
  total: number;
  skip: number;
  limit: number;
}
