/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { Creator } from './creator';

export interface CreatorPage {
  /** Paginated list of creators. */
  items: Creator[];
  /** Total number of creators matching the query. */
  total: number;
  /** Number of items skipped. */
  skip: number;
  /** Maximum number of items returned. */
  limit: number;
}
