/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * ID of a representative image to use as the creator's avatar/cover.
 */
export type CreatorStatsPreviewImageId = number | null;
