/**
 * @file
 * Module defining the CreatorCreateNotes type.
 * This model is auto-generated by Orval from the backend OpenAPI specification.
 * It represents the notes field used when creating a new creator.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type CreatorCreateNotes = string | null;
