/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface Creator {
  canonical_name: string;
  type?: string | null;
  notes?: string | null;
  id: number;
}
