/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CreatorStatsPrimaryAspectRatio } from './creatorStatsPrimaryAspectRatio';
import type { CreatorStatsPreviewImageId } from './creatorStatsPreviewImageId';

export interface CreatorStats {
  total_sets?: number;
  total_images?: number;
  total_size_bytes?: number;
  primary_aspect_ratio?: CreatorStatsPrimaryAspectRatio;
  preview_image_id?: CreatorStatsPreviewImageId;
}
