/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Type of creator (e.g., 'photographer', 'illustrator', 'cosplayer').
 */
export type CreatorType = string | null;
