/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { LibraryStats } from './libraryStats';
import type { HealthAlert } from './healthAlert';

export interface DashboardData {
  /** Aggregated statistics for the entire library. */
  stats: LibraryStats;
  /** Active health and maintenance alerts requiring user attention. */
  health_alerts: HealthAlert[];
}
