/**
 * @file
 * Defines the API model for DashboardData.
 * Contains aggregated library statistics and health alerts for the main dashboard.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { LibraryStats } from './libraryStats';
import type { HealthAlert } from './healthAlert';

export interface DashboardData {
  stats: LibraryStats;
  health_alerts: HealthAlert[];
}
