/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface DuplicateResolutionRequest {
  /** The ID of the image to keep. All others will be deleted. */
  keep_image_id: number;
  /** List of image IDs to permanently delete from disk and database. */
  remove_image_ids: number[];
}
