/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ImageWithContext } from './imageWithContext';

export interface DuplicateGroup {
  /** The perceptual hash shared by this group of duplicates. */
  phash: string;
  /** List of visually similar images in this group. */
  images: ImageWithContext[];
  /** The ID of the image recommended to be kept (usually highest resolution). */
  recommended_keep_id: number;
}
