/**
 * @file
 * Defines the API model for DuplicateGroup.
 * Represents a group of identical or similar images identified by their pHash.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ImageWithContext } from './imageWithContext';

export interface DuplicateGroup {
  phash: string;
  images: ImageWithContext[];
  recommended_keep_id: number;
}
