/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface DuplicateResolutionRequest {
  keep_image_id: number;
  remove_image_ids: number[];
}
