/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface FranchiseMerge {
  /** List of franchise IDs to merge and delete. */
  source_ids: number[];
  /** The ID of the franchise to merge into. */
  target_id: number;
}
