/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { FranchiseUpdateName } from './franchiseUpdateName';

export interface FranchiseUpdate {
  /** The updated name of the franchise. */
  name?: FranchiseUpdateName;
}
