/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * The updated name of the franchise.
 */
export type FranchiseUpdateName = string | null;
