/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface Franchise {
  /** The name of the franchise. */
  name: string;
  /** Unique database identifier for the franchise. */
  id: number;
  /** Number of sets featuring characters from this franchise. */
  set_count?: number;
}
