/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type GetAuditResultsApiAuditResultsGetParams = {
skip?: number;
limit?: number;
issue_type?: string | null;
status?: string;
};
