/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface HealthAlert {
  /** Unique identifier for this type of alert. */
  id: string;
  /** Severity level of the alert: 'critical', 'warning', or 'optimization'. */
  severity: string;
  /** Human-readable description of the issue. */
  message: string;
  /** Number of items affected by this issue. */
  count: number;
  /** Navigation path to the tool or view where the issue can be resolved. */
  link: string;
}
