/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface HealthAlert {
  id: string;
  severity: string;
  message: string;
  count: number;
  link: string;
}
