/**
 * @file
 * Defines the API model for HTTPValidationError.
 * Represents validation errors returned by the FastAPI backend.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ValidationError } from './validationError';

export interface HTTPValidationError {
  detail?: ValidationError[];
}
