/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ImageCreatePhash } from './imageCreatePhash';
import type { ImageCreateWidth } from './imageCreateWidth';
import type { ImageCreateHeight } from './imageCreateHeight';
import type { ImageCreateFileSize } from './imageCreateFileSize';
import type { ImageCreateAspectRatio } from './imageCreateAspectRatio';
import type { ImageCreateAspectRatioLabel } from './imageCreateAspectRatioLabel';
import type { ImageCreateSortOrder } from './imageCreateSortOrder';
import type { ImageCreateNotes } from './imageCreateNotes';

export interface ImageCreate {
  filename: string;
  local_path: string;
  phash?: ImageCreatePhash;
  width?: ImageCreateWidth;
  height?: ImageCreateHeight;
  file_size?: ImageCreateFileSize;
  aspect_ratio?: ImageCreateAspectRatio;
  aspect_ratio_label?: ImageCreateAspectRatioLabel;
  sort_order?: ImageCreateSortOrder;
  notes?: ImageCreateNotes;
}
