/**
 * @file
 * Module: imageUpdatePhash.ts
 * Description: Defines the ImageUpdatePhash type for the API model.
 * Represents the updated perceptual hash for deduplicating an image.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ImageUpdatePhash = string | null;
