/**
 * @file
 * Module: imageNotes.ts
 * Description: Defines the ImageNotes type for the API model.
 * Represents user-defined or metadata notes associated with an image.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ImageNotes = string | null;
