/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Hex code of the dominant color.
 */
export type ImageUpdateDominantColor = string | null;
