/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Global set name/title to assign by default.
 */
export type ImageImportRequestSetTitle = string | null;
