/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface ImageImportValidationRequest {
  /** List of local absolute file paths (files or folders) to validate. */
  local_paths: string[];
}
