/**
 * Module: imageUpdateFileSize.ts
 * Description: Defines the ImageUpdateFileSize type for the API model.
 * Represents the updated file size of an image in bytes.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ImageUpdateFileSize = number | null;
