/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Global set ID to import into, if assigning to an existing set.
 */
export type ImageImportRequestSetId = number | null;
