/**
 * Module: imageHeight.ts
 * Description: Defines the ImageHeight type for the API model.
 * Represents the vertical resolution of an image in pixels.
 */
/**
 * Defines the API model for ImageHeight.
 * Represents the height of a stored image in pixels.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ImageHeight = number | null;
