/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Global tags to assign to all imported files.
 */
export type ImageImportRequestTags = string[] | null;
