/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * User-provided notes or description for the image.
 */
export type ImageUpdateNotes = string | null;
