/**
 * Module: imageWithContextAspectRatioLabel.ts
 * Description: Defines the ImageWithContextAspectRatioLabel type for the API model.
 * Represents the human-readable aspect ratio label within an ImageWithContext structure.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ImageWithContextAspectRatioLabel = string | null;
