/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ImageDetailPhash } from './imageDetailPhash';
import type { ImageDetailWidth } from './imageDetailWidth';
import type { ImageDetailHeight } from './imageDetailHeight';
import type { ImageDetailFileSize } from './imageDetailFileSize';
import type { ImageDetailAspectRatio } from './imageDetailAspectRatio';
import type { ImageDetailAspectRatioLabel } from './imageDetailAspectRatioLabel';
import type { ImageDetailSortOrder } from './imageDetailSortOrder';
import type { ImageDetailNotes } from './imageDetailNotes';
import type { ImageDetailRating } from './imageDetailRating';
import type { ImageDetailDominantColor } from './imageDetailDominantColor';
import type { ImageDetailFocalPointX } from './imageDetailFocalPointX';
import type { ImageDetailFocalPointY } from './imageDetailFocalPointY';

export interface ImageDetail {
  /** The original filename of the image. */
  filename: string;
  /** The absolute local path to the image file on disk. */
  local_path: string;
  /** Perceptual hash used to detect visually similar or duplicate images. */
  phash?: ImageDetailPhash;
  /** Image width in pixels. */
  width?: ImageDetailWidth;
  /** Image height in pixels. */
  height?: ImageDetailHeight;
  /** Image file size in bytes. */
  file_size?: ImageDetailFileSize;
  /** Calculated aspect ratio (width / height). */
  aspect_ratio?: ImageDetailAspectRatio;
  /** Human-readable aspect ratio label (e.g., '16:9', 'Ultrawide'). */
  aspect_ratio_label?: ImageDetailAspectRatioLabel;
  /** Display order within a set. Lower numbers appear first. */
  sort_order?: ImageDetailSortOrder;
  /** User-provided notes or description for the image. */
  notes?: ImageDetailNotes;
  /** Content rating (e.g., 'safe', 'questionable', 'explicit'). */
  rating?: ImageDetailRating;
  /** Hex code of the image's dominant color extracted during import. */
  dominant_color?: ImageDetailDominantColor;
  /** Computed X percentage for the focal point. */
  focal_point_x?: ImageDetailFocalPointX;
  /** Computed Y percentage for the focal point. */
  focal_point_y?: ImageDetailFocalPointY;
  /** Whether this image is marked as a favorite wallpaper. */
  is_favorite?: boolean;
  /** Whether this image is blacklisted from rotations. */
  is_blacklisted?: boolean;
  /** Unique database identifier for the image. */
  id: number;
  /** ID of the set this image belongs to. */
  set_id: number;
  /** Timestamp when the image was added to the database. */
  date_added: string;
  /** List of descriptive tag names for the image. */
  tags?: string[];
}
