/**
 * Defines the API model for ImageCreatePhash.
 * Represents the perceptual hash property during image creation.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ImageCreatePhash = string | null;
