/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Target aspect ratio, e.g. '16:9', '21:9', '16:10', '9:16'
 */
export type ImageCropRequestAspectRatio = string | null;
