/**
 * @file
 * Module: imageRating.ts
 * Description: Defines the ImageRating type for the API model.
 * Represents a qualitative or numerical rating given to an image.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ImageRating = string | null;
