/**
 * Module: imageUpdateSortOrder.ts
 * Description: Defines the ImageUpdateSortOrder type for the API model.
 * Represents the updated display sort order for an image.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ImageUpdateSortOrder = number | null;
