/**
 * @file
 * Module: imageUpdateAspectRatioLabel.ts
 * Description: Defines the ImageUpdateAspectRatioLabel type for the API model.
 * Represents the updated human-readable aspect ratio label.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ImageUpdateAspectRatioLabel = string | null;
