/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ImagePhash } from './imagePhash';
import type { ImageWidth } from './imageWidth';
import type { ImageHeight } from './imageHeight';
import type { ImageFileSize } from './imageFileSize';
import type { ImageAspectRatio } from './imageAspectRatio';
import type { ImageAspectRatioLabel } from './imageAspectRatioLabel';
import type { ImageSortOrder } from './imageSortOrder';
import type { ImageNotes } from './imageNotes';
import type { ImageRating } from './imageRating';
import type { ImageDominantColor } from './imageDominantColor';
import type { ImageFocalPointX } from './imageFocalPointX';
import type { ImageFocalPointY } from './imageFocalPointY';

export interface Image {
  /** The original filename of the image. */
  filename: string;
  /** The absolute local path to the image file on disk. */
  local_path: string;
  /** Perceptual hash used to detect visually similar or duplicate images. */
  phash?: ImagePhash;
  /** Image width in pixels. */
  width?: ImageWidth;
  /** Image height in pixels. */
  height?: ImageHeight;
  /** Image file size in bytes. */
  file_size?: ImageFileSize;
  /** Calculated aspect ratio (width / height). */
  aspect_ratio?: ImageAspectRatio;
  /** Human-readable aspect ratio label (e.g., '16:9', 'Ultrawide'). */
  aspect_ratio_label?: ImageAspectRatioLabel;
  /** Display order within a set. Lower numbers appear first. */
  sort_order?: ImageSortOrder;
  /** User-provided notes or description for the image. */
  notes?: ImageNotes;
  /** Content rating (e.g., 'safe', 'questionable', 'explicit'). */
  rating?: ImageRating;
  /** Hex code of the image's dominant color extracted during import. */
  dominant_color?: ImageDominantColor;
  /** Computed X percentage for the focal point. */
  focal_point_x?: ImageFocalPointX;
  /** Computed Y percentage for the focal point. */
  focal_point_y?: ImageFocalPointY;
  /** Whether this image is marked as a favorite wallpaper. */
  is_favorite?: boolean;
  /** Whether this image is blacklisted from rotations. */
  is_blacklisted?: boolean;
  /** Unique database identifier for the image. */
  id: number;
  /** ID of the set this image belongs to. */
  set_id: number;
  /** Timestamp when the image was added to the database. */
  date_added: string;
}
