/**
 * @file
 * Defines the API model for ImageCreateDominantColor.
 * Represents the dominant color property during image creation.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ImageCreateDominantColor = string | null;
