/**
 * Module: imageUpdateWidth.ts
 * Description: Defines the ImageUpdateWidth type for the API model.
 * Represents the updated width resolution for an image.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ImageUpdateWidth = number | null;
