/**
 * Defines the ImageWithContextTags model.
 * Represents the tags associated with an image within its context.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ImageWithContextTags = string | null;
