/**
 * Module: imagePhash.ts
 * Description: Defines the ImagePhash type for the API model.
 * Represents the perceptual hash of an image used for deduplication.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ImagePhash = string | null;
