/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ImageUpdate } from './imageUpdate';
import type { BulkOperationMode } from './bulkOperationMode';

export interface ImageBulkUpdate {
  image_ids: number[];
  update_data: ImageUpdate;
  operation_mode?: BulkOperationMode;
}
