/**
 * Module: imagePage.ts
 * Description: Defines the ImagePage interface for the API model.
 * Used for paginated responses of ImageWithContext items.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ImageWithContext } from './imageWithContext';

export interface ImagePage {
  items: ImageWithContext[];
  total: number;
  skip: number;
  limit: number;
}
