/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Hex code of the image's dominant color extracted during import.
 */
export type ImageDetailDominantColor = string | null;
