/**
 * @file
 * Module: imageUpdateTags.ts
 * Description: Defines the ImageUpdateTags type for the API model.
 * Represents the updated comma-separated string of tags for an image.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ImageUpdateTags = string | null;
