/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Display order within a set. Lower numbers appear first.
 */
export type ImageWithContextSortOrder = number | null;
