/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface ImageBulkMove {
  /** List of image IDs to move. */
  image_ids: number[];
  /** The ID of the destination set. */
  target_set_id: number;
}
