/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ImageWithContextPhash } from './imageWithContextPhash';
import type { ImageWithContextWidth } from './imageWithContextWidth';
import type { ImageWithContextHeight } from './imageWithContextHeight';
import type { ImageWithContextFileSize } from './imageWithContextFileSize';
import type { ImageWithContextAspectRatio } from './imageWithContextAspectRatio';
import type { ImageWithContextAspectRatioLabel } from './imageWithContextAspectRatioLabel';
import type { ImageWithContextSortOrder } from './imageWithContextSortOrder';
import type { ImageWithContextNotes } from './imageWithContextNotes';

export interface ImageWithContext {
  filename: string;
  local_path: string;
  phash?: ImageWithContextPhash;
  width?: ImageWithContextWidth;
  height?: ImageWithContextHeight;
  file_size?: ImageWithContextFileSize;
  aspect_ratio?: ImageWithContextAspectRatio;
  aspect_ratio_label?: ImageWithContextAspectRatioLabel;
  sort_order?: ImageWithContextSortOrder;
  notes?: ImageWithContextNotes;
  id: number;
  set_id: number;
  date_added: string;
  set_title: string;
  creator_names: string[];
}
