/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Perceptual hash used to detect visually similar or duplicate images.
 */
export type ImageWithContextPhash = string | null;
