/**
 * Module: imageUpdateHeight.ts
 * Description: Defines the ImageUpdateHeight type for the API model.
 * Represents the updated height resolution of an image.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ImageUpdateHeight = number | null;
