/**
 * Module: imageUpdateNotes.ts
 * Description: Defines the ImageUpdateNotes type for the API model.
 * Represents the updated user notes or metadata for an image.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ImageUpdateNotes = string | null;
