/**
 * Module: imageWidth.ts
 * Description: Defines the ImageWidth type for the API model.
 * Represents the horizontal resolution of an image in pixels.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ImageWidth = number | null;
