/**
 * @file
 * Module: imageUpdateAspectRatio.ts
 * Description: Defines the ImageUpdateAspectRatio type for the API model.
 * Represents the updated aspect ratio value for an image.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ImageUpdateAspectRatio = number | null;
