/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Top-left Y coordinate for custom crop
 */
export type ImageCropRequestY = number | null;
