/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ImageImportItemFilename } from './imageImportItemFilename';
import type { ImageImportItemRating } from './imageImportItemRating';
import type { ImageImportItemTags } from './imageImportItemTags';

export interface ImageImportItem {
  local_path: string;
  filename?: ImageImportItemFilename;
  rating?: ImageImportItemRating;
  tags?: ImageImportItemTags;
}
