/**
 * Module: imageUpdateDominantColor.ts
 * Description: Defines the ImageUpdateDominantColor type for the API model.
 * Represents the updated dominant color code for an image.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ImageUpdateDominantColor = string | null;
