/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ImageCropResponseX } from './imageCropResponseX';
import type { ImageCropResponseY } from './imageCropResponseY';
import type { ImageCropResponseWidth } from './imageCropResponseWidth';
import type { ImageCropResponseHeight } from './imageCropResponseHeight';
import type { ImageCropResponseImage } from './imageCropResponseImage';

export interface ImageCropResponse {
  /** Calculated top-left X coordinate */
  x?: ImageCropResponseX;
  /** Calculated top-left Y coordinate */
  y?: ImageCropResponseY;
  /** Calculated crop width */
  width?: ImageCropResponseWidth;
  /** Calculated crop height */
  height?: ImageCropResponseHeight;
  /** The resulting image object (populated when preview_only=False) */
  image?: ImageCropResponseImage;
}
