/**
 * @file
 * Module: imageUpdateFilename.ts
 * Description: Defines the ImageUpdateFilename type for the API model.
 * Represents the updated filename of an image.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ImageUpdateFilename = string | null;
