/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ImageUpdateFilename } from './imageUpdateFilename';
import type { ImageUpdateNotes } from './imageUpdateNotes';
import type { ImageUpdateSortOrder } from './imageUpdateSortOrder';
import type { ImageUpdatePhash } from './imageUpdatePhash';
import type { ImageUpdateWidth } from './imageUpdateWidth';
import type { ImageUpdateHeight } from './imageUpdateHeight';
import type { ImageUpdateFileSize } from './imageUpdateFileSize';
import type { ImageUpdateAspectRatio } from './imageUpdateAspectRatio';
import type { ImageUpdateAspectRatioLabel } from './imageUpdateAspectRatioLabel';
import type { ImageUpdateLocalPath } from './imageUpdateLocalPath';
import type { ImageUpdateRating } from './imageUpdateRating';
import type { ImageUpdateDominantColor } from './imageUpdateDominantColor';
import type { ImageUpdateTags } from './imageUpdateTags';

export interface ImageUpdate {
  /** The original filename of the image. */
  filename?: ImageUpdateFilename;
  /** User-provided notes or description for the image. */
  notes?: ImageUpdateNotes;
  /** Display order within a set. */
  sort_order?: ImageUpdateSortOrder;
  /** Perceptual hash. */
  phash?: ImageUpdatePhash;
  /** Image width in pixels. */
  width?: ImageUpdateWidth;
  /** Image height in pixels. */
  height?: ImageUpdateHeight;
  /** Image file size in bytes. */
  file_size?: ImageUpdateFileSize;
  /** Calculated aspect ratio. */
  aspect_ratio?: ImageUpdateAspectRatio;
  /** Human-readable aspect ratio label. */
  aspect_ratio_label?: ImageUpdateAspectRatioLabel;
  /** The absolute local path to the image file. */
  local_path?: ImageUpdateLocalPath;
  /** Content rating. */
  rating?: ImageUpdateRating;
  /** Hex code of the dominant color. */
  dominant_color?: ImageUpdateDominantColor;
  /** Comma-separated tags. */
  tags?: ImageUpdateTags;
}
