/**
 * @file
 * Module: imageWithContextAspectRatio.ts
 * Description: Defines the ImageWithContextAspectRatio type for the API model.
 * Represents the aspect ratio within an ImageWithContext structure.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ImageWithContextAspectRatio = number | null;
