/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Whether this image is marked as a favorite wallpaper.
 */
export type ImageUpdateIsFavorite = boolean | null;
