/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ImageImportItem } from './imageImportItem';
import type { ImageImportRequestCreatorName } from './imageImportRequestCreatorName';
import type { ImageImportRequestSetTitle } from './imageImportRequestSetTitle';
import type { ImageImportRequestSetId } from './imageImportRequestSetId';
import type { ImageImportRequestTags } from './imageImportRequestTags';
import type { ImageImportRequestRating } from './imageImportRequestRating';

export interface ImageImportRequest {
  /** List of items to import. */
  items: ImageImportItem[];
  /** Global creator/artist to assign by default. */
  creator_name?: ImageImportRequestCreatorName;
  /** Global set name/title to assign by default. */
  set_title?: ImageImportRequestSetTitle;
  /** Global set ID to import into, if assigning to an existing set. */
  set_id?: ImageImportRequestSetId;
  /** Global tags to assign to all imported files. */
  tags?: ImageImportRequestTags;
  /** Global content rating. */
  rating?: ImageImportRequestRating;
  /** Whether to delete source files after successful import. */
  delete_source?: boolean;
}
