/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Content rating (e.g., 'safe', 'questionable', 'explicit').
 */
export type ImageDetailRating = string | null;
