/**
 * @file
 * Module: imageTags.ts
 * Description: Defines the ImageTags type for the API model.
 * Represents a comma-separated string or serialized list of tags for an image.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ImageTags = string | null;
