/**
 * Module: imageUpdateRating.ts
 * Description: Defines the ImageUpdateRating type for the API model.
 * Represents the updated qualitative or numerical rating for an image.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ImageUpdateRating = string | null;
