/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ImageUpdateFilename } from './imageUpdateFilename';
import type { ImageUpdateLocalPath } from './imageUpdateLocalPath';
import type { ImageUpdatePhash } from './imageUpdatePhash';
import type { ImageUpdateWidth } from './imageUpdateWidth';
import type { ImageUpdateHeight } from './imageUpdateHeight';
import type { ImageUpdateFileSize } from './imageUpdateFileSize';
import type { ImageUpdateAspectRatio } from './imageUpdateAspectRatio';
import type { ImageUpdateAspectRatioLabel } from './imageUpdateAspectRatioLabel';
import type { ImageUpdateSortOrder } from './imageUpdateSortOrder';
import type { ImageUpdateNotes } from './imageUpdateNotes';

export interface ImageUpdate {
  filename?: ImageUpdateFilename;
  local_path?: ImageUpdateLocalPath;
  phash?: ImageUpdatePhash;
  width?: ImageUpdateWidth;
  height?: ImageUpdateHeight;
  file_size?: ImageUpdateFileSize;
  aspect_ratio?: ImageUpdateAspectRatio;
  aspect_ratio_label?: ImageUpdateAspectRatioLabel;
  sort_order?: ImageUpdateSortOrder;
  notes?: ImageUpdateNotes;
}
