/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Calculated aspect ratio (width / height).
 */
export type ImageAspectRatio = number | null;
