/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ImageValidationItemError } from './imageValidationItemError';
import type { ImageValidationItemPhash } from './imageValidationItemPhash';
import type { ImageValidationItemExistingImageId } from './imageValidationItemExistingImageId';
import type { ImageValidationItemExistingSetTitle } from './imageValidationItemExistingSetTitle';

export interface ImageValidationItem {
  local_path: string;
  filename: string;
  is_valid: boolean;
  error?: ImageValidationItemError;
  phash?: ImageValidationItemPhash;
  is_duplicate: boolean;
  existing_image_id?: ImageValidationItemExistingImageId;
  existing_set_title?: ImageValidationItemExistingSetTitle;
  existing_creator_names?: string[];
}
