/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ImageDetail } from './imageDetail';

/**
 * The resulting image object (populated when preview_only=False)
 */
export type ImageCropResponseImage = ImageDetail | null;
