/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Comma-separated string of descriptive tags.
 */
export type ImageWithContextTags = string | null;
