/**
 * @file
 * Module: imageSortOrder.ts
 * Description: Defines the ImageSortOrder type for the API model.
 * Represents the display or logical sort order for an image.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ImageSortOrder = number | null;
