/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ImageWithContext } from './imageWithContext';

export interface ImagePage {
  /** Paginated list of images. */
  items: ImageWithContext[];
  /** Total number of images matching the query. */
  total: number;
  /** Number of items skipped. */
  skip: number;
  /** Maximum number of items returned. */
  limit: number;
}
