/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ImageCropRequestAspectRatio } from './imageCropRequestAspectRatio';
import type { ImageCropRequestX } from './imageCropRequestX';
import type { ImageCropRequestY } from './imageCropRequestY';
import type { ImageCropRequestWidth } from './imageCropRequestWidth';
import type { ImageCropRequestHeight } from './imageCropRequestHeight';

export interface ImageCropRequest {
  /** Target aspect ratio, e.g. '16:9', '21:9', '16:10', '9:16' */
  aspect_ratio?: ImageCropRequestAspectRatio;
  /** Top-left X coordinate for custom crop */
  x?: ImageCropRequestX;
  /** Top-left Y coordinate for custom crop */
  y?: ImageCropRequestY;
  /** Width for custom crop */
  width?: ImageCropRequestWidth;
  /** Height for custom crop */
  height?: ImageCropRequestHeight;
  /** Save mode: 'new' or 'replace' */
  save_mode?: string;
  /** If True, only return the calculated crop coordinates without performing the crop operation */
  preview_only?: boolean;
}
