/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ImageWithContext } from './imageWithContext';

export interface ImagePage {
  items: ImageWithContext[];
  total: number;
  skip: number;
  limit: number;
}
