/**
 * Module: imageUpdateLocalPath.ts
 * Description: Defines the ImageUpdateLocalPath type for the API model.
 * Represents the updated local storage path of an image.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ImageUpdateLocalPath = string | null;
