/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ImageWithContextPhash } from './imageWithContextPhash';
import type { ImageWithContextWidth } from './imageWithContextWidth';
import type { ImageWithContextHeight } from './imageWithContextHeight';
import type { ImageWithContextFileSize } from './imageWithContextFileSize';
import type { ImageWithContextAspectRatio } from './imageWithContextAspectRatio';
import type { ImageWithContextAspectRatioLabel } from './imageWithContextAspectRatioLabel';
import type { ImageWithContextSortOrder } from './imageWithContextSortOrder';
import type { ImageWithContextNotes } from './imageWithContextNotes';
import type { ImageWithContextRating } from './imageWithContextRating';
import type { ImageWithContextDominantColor } from './imageWithContextDominantColor';
import type { ImageWithContextFocalPointX } from './imageWithContextFocalPointX';
import type { ImageWithContextFocalPointY } from './imageWithContextFocalPointY';

export interface ImageWithContext {
  /** The original filename of the image. */
  filename: string;
  /** The absolute local path to the image file on disk. */
  local_path: string;
  /** Perceptual hash used to detect visually similar or duplicate images. */
  phash?: ImageWithContextPhash;
  /** Image width in pixels. */
  width?: ImageWithContextWidth;
  /** Image height in pixels. */
  height?: ImageWithContextHeight;
  /** Image file size in bytes. */
  file_size?: ImageWithContextFileSize;
  /** Calculated aspect ratio (width / height). */
  aspect_ratio?: ImageWithContextAspectRatio;
  /** Human-readable aspect ratio label (e.g., '16:9', 'Ultrawide'). */
  aspect_ratio_label?: ImageWithContextAspectRatioLabel;
  /** Display order within a set. Lower numbers appear first. */
  sort_order?: ImageWithContextSortOrder;
  /** User-provided notes or description for the image. */
  notes?: ImageWithContextNotes;
  /** Content rating (e.g., 'safe', 'questionable', 'explicit'). */
  rating?: ImageWithContextRating;
  /** Hex code of the image's dominant color extracted during import. */
  dominant_color?: ImageWithContextDominantColor;
  /** Computed X percentage for the focal point. */
  focal_point_x?: ImageWithContextFocalPointX;
  /** Computed Y percentage for the focal point. */
  focal_point_y?: ImageWithContextFocalPointY;
  /** Whether this image is marked as a favorite wallpaper. */
  is_favorite?: boolean;
  /** Whether this image is blacklisted from rotations. */
  is_blacklisted?: boolean;
  /** Unique database identifier for the image. */
  id: number;
  /** ID of the set this image belongs to. */
  set_id: number;
  /** Timestamp when the image was added to the database. */
  date_added: string;
  /** The title of the set this image belongs to. */
  set_title: string;
  /** List of creator names associated with this image's set. */
  creator_names: string[];
}
