/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ImagePhash } from './imagePhash';
import type { ImageWidth } from './imageWidth';
import type { ImageHeight } from './imageHeight';
import type { ImageFileSize } from './imageFileSize';
import type { ImageAspectRatio } from './imageAspectRatio';
import type { ImageAspectRatioLabel } from './imageAspectRatioLabel';
import type { ImageSortOrder } from './imageSortOrder';
import type { ImageNotes } from './imageNotes';

export interface Image {
  filename: string;
  local_path: string;
  phash?: ImagePhash;
  width?: ImageWidth;
  height?: ImageHeight;
  file_size?: ImageFileSize;
  aspect_ratio?: ImageAspectRatio;
  aspect_ratio_label?: ImageAspectRatioLabel;
  sort_order?: ImageSortOrder;
  notes?: ImageNotes;
  id: number;
  set_id: number;
  date_added: string;
}
