/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ImageCreatePhash } from './imageCreatePhash';
import type { ImageCreateWidth } from './imageCreateWidth';
import type { ImageCreateHeight } from './imageCreateHeight';
import type { ImageCreateFileSize } from './imageCreateFileSize';
import type { ImageCreateAspectRatio } from './imageCreateAspectRatio';
import type { ImageCreateAspectRatioLabel } from './imageCreateAspectRatioLabel';
import type { ImageCreateSortOrder } from './imageCreateSortOrder';
import type { ImageCreateNotes } from './imageCreateNotes';
import type { ImageCreateRating } from './imageCreateRating';
import type { ImageCreateDominantColor } from './imageCreateDominantColor';
import type { ImageCreateFocalPointX } from './imageCreateFocalPointX';
import type { ImageCreateFocalPointY } from './imageCreateFocalPointY';

export interface ImageCreate {
  /** The original filename of the image. */
  filename: string;
  /** The absolute local path to the image file on disk. */
  local_path: string;
  /** Perceptual hash used to detect visually similar or duplicate images. */
  phash?: ImageCreatePhash;
  /** Image width in pixels. */
  width?: ImageCreateWidth;
  /** Image height in pixels. */
  height?: ImageCreateHeight;
  /** Image file size in bytes. */
  file_size?: ImageCreateFileSize;
  /** Calculated aspect ratio (width / height). */
  aspect_ratio?: ImageCreateAspectRatio;
  /** Human-readable aspect ratio label (e.g., '16:9', 'Ultrawide'). */
  aspect_ratio_label?: ImageCreateAspectRatioLabel;
  /** Display order within a set. Lower numbers appear first. */
  sort_order?: ImageCreateSortOrder;
  /** User-provided notes or description for the image. */
  notes?: ImageCreateNotes;
  /** Content rating (e.g., 'safe', 'questionable', 'explicit'). */
  rating?: ImageCreateRating;
  /** Hex code of the image's dominant color extracted during import. */
  dominant_color?: ImageCreateDominantColor;
  /** Computed X percentage for the focal point. */
  focal_point_x?: ImageCreateFocalPointX;
  /** Computed Y percentage for the focal point. */
  focal_point_y?: ImageCreateFocalPointY;
}
