/**
 * Defines the LibraryStatsAspectRatioDistribution model.
 * Represents the distribution of aspect ratios within the library.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type LibraryStatsAspectRatioDistribution = {[key: string]: number};
