/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { LibraryStatsAspectRatioDistribution } from './libraryStatsAspectRatioDistribution';

export interface LibraryStats {
  /** Total number of images in the vault. */
  total_images: number;
  /** Total number of sets in the vault. */
  total_sets: number;
  /** Total number of unique creators. */
  total_creators: number;
  /** Total disk space used by all images in bytes. */
  total_size_bytes: number;
  /** Size of the SQLite database file on disk in bytes. */
  database_size_bytes: number;
  /** Histogram mapping aspect ratio labels to the count of images. */
  aspect_ratio_distribution: LibraryStatsAspectRatioDistribution;
}
