/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Histogram mapping aspect ratio labels to the count of images.
 */
export type LibraryStatsAspectRatioDistribution = {[key: string]: number};
