/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { LibraryStatsAspectRatioDistribution } from './libraryStatsAspectRatioDistribution';

export interface LibraryStats {
  total_images: number;
  total_sets: number;
  total_creators: number;
  total_size_bytes: number;
  aspect_ratio_distribution: LibraryStatsAspectRatioDistribution;
}
