/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { PlaylistCreateDescription } from './playlistCreateDescription';

export interface PlaylistCreate {
  /** The name of the playlist. */
  name: string;
  /** Optional description of the playlist. */
  description?: PlaylistCreateDescription;
}
