/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { Image } from './image';

export interface PlaylistImageDetail {
  /** The image object. */
  image: Image;
  /** The position of the image in the playlist. */
  sort_order: number;
}
