/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface PlaylistImagesReorder {
  /** Ordered list of image IDs representing the new sequence. */
  image_ids: number[];
}
