/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { PlaylistUpdateName } from './playlistUpdateName';
import type { PlaylistUpdateDescription } from './playlistUpdateDescription';

export interface PlaylistUpdate {
  /** The updated name of the playlist. */
  name?: PlaylistUpdateName;
  /** The updated description of the playlist. */
  description?: PlaylistUpdateDescription;
}
