/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface PlaylistImagesRemove {
  /** List of image IDs to remove from the playlist. */
  image_ids: number[];
}
