/**
 * @file
 * Defines the ReadImagesApiImagesGetParams model.
 * Represents parameters for fetching images from the API.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ReadImagesApiImagesGetParams = {
skip?: number;
limit?: number;
search?: string | null;
rating?: string | null;
};
