/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ReadCreatorsApiCreatorsGetParams = {
skip?: number;
limit?: number;
search?: string | null;
creator_type?: string | null;
/**
 * Sort field (name, set_count, total_image_count)
 */
sort_by?: string | null;
/**
 * Sort direction (asc, desc)
 */
sort_dir?: string | null;
};
