/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ReadTagCloudApiTagsCloudGetParams = {
/**
 * Maximum number of tags to return, sorted by frequency
 */
limit?: number;
};
