/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ReadRandomImageFileApiImagesRandomFileGetParams = {
tags?: string[] | null;
aspect_ratio_label?: string | null;
min_width?: number | null;
min_height?: number | null;
creator_id?: number | null;
};
