/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ReadImagesApiImagesGetParams = {
skip?: number;
limit?: number;
search?: string | null;
rating?: string | null;
/**
 * Filter by a single tag (matches image or set tags)
 */
tag?: string | null;
/**
 * Filter by dominant color bucket
 */
color?: string | null;
/**
 * Filter by character names
 */
character?: string[] | null;
/**
 * Filter by franchise names
 */
franchise?: string[] | null;
/**
 * Sort field (date_added, file_size, resolution, rating, aspect_ratio, random)
 */
sort_by?: string | null;
/**
 * Direction to sort
 */
sort_dir?: string | null;
};
