/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ReadImagesApiImagesGetParams = {
skip?: number;
limit?: number;
search?: string | null;
rating?: string | null;
/**
 * Sort field (date_added, file_size, resolution, rating, aspect_ratio, random)
 */
sort_by?: string | null;
/**
 * Sort direction (asc, desc)
 */
sort_dir?: string | null;
};
