/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Contextual metadata (e.g. set count or creator name).
 */
export type SearchResultItemDetail = string | null;
