/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type SearchTagsApiTagsGetParams = {
/**
 * Prefix or keyword to search for in tags
 */
q?: string | null;
/**
 * Maximum number of tags to return
 */
limit?: number;
};
