/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SearchResultItemId } from './searchResultItemId';
import type { SearchResultItemDetail } from './searchResultItemDetail';

/**
 * A single matched item in the global fuzzy search results.
 */
export interface SearchResultItem {
  /** Unique ID of the matched record. */
  id: SearchResultItemId;
  /** Main name or title of the matched item. */
  name: string;
  /** Entity type: set, creator, character, franchise, or tag. */
  type: string;
  /** Contextual metadata (e.g. set count or creator name). */
  detail?: SearchResultItemDetail;
}
