/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Unique ID of the matched record.
 */
export type SearchResultItemId = number | string;
