/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type SearchAllApiSearchGetParams = {
/**
 * The search term
 * @minLength 1
 */
q: string;
};
