/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SetTitle } from './setTitle';
import type { SetSourceUrl } from './setSourceUrl';
import type { SetLocalPath } from './setLocalPath';
import type { SetPhash } from './setPhash';
import type { SetNotes } from './setNotes';
import type { Creator } from './creator';
import type { Image } from './image';

export interface Set {
  /** The display title of the set. */
  title?: SetTitle;
  /** Original URL where the set was downloaded from. */
  source_url?: SetSourceUrl;
  /** Local filesystem path where the set's files reside. */
  local_path?: SetLocalPath;
  /** Perceptual hash representative of the set (usually the cover image). */
  phash?: SetPhash;
  /** User-provided notes or context for the set. */
  notes?: SetNotes;
  /** List of descriptive tag names for the set. */
  tags?: string[];
  /** List of character names for the set. */
  characters?: string[];
  /** Unique database identifier for the set. */
  id: number;
  /** Timestamp when the set was added to the vault. */
  date_added: string;
  /** List of creators associated with this set. */
  creators?: Creator[];
  /** List of images contained in this set. */
  images?: Image[];
}
