/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { Creator } from './creator';

export interface Set {
  title?: string | null;
  source_url?: string | null;
  local_path?: string | null;
  phash?: string | null;
  notes?: string | null;
  id: number;
  date_added: string;
  creators?: Creator[];
}
