/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Explicit set title to assign. If null, attempts to extract from path.
 */
export type SetBatchImportSetTitle = string | null;
