/**
 * Defines the SetBatchImportCreatorName model.
 * Represents the creator name during a set batch import.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type SetBatchImportCreatorName = string | null;
