/**
 * @file
 * Defines the SetBulkUpdate model.
 * Represents a bulk update payload for sets.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SetUpdate } from './setUpdate';
import type { BulkOperationMode } from './bulkOperationMode';

export interface SetBulkUpdate {
  set_ids: number[];
  update_data: SetUpdate;
  operation_mode?: BulkOperationMode;
}
