/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SetBatchImportCreatorName } from './setBatchImportCreatorName';
import type { SetBatchImportSetTitle } from './setBatchImportSetTitle';

export interface SetBatchImport {
  source_path: string;
  creator_name?: SetBatchImportCreatorName;
  set_title?: SetBatchImportSetTitle;
  delete_source?: boolean;
  auto_orient?: boolean;
}
