/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SetUpdate } from './setUpdate';
import type { BulkOperationMode } from './bulkOperationMode';

export interface SetBulkUpdate {
  /** List of set IDs to apply the bulk update to. */
  set_ids: number[];
  /** The data to apply to all selected sets. */
  update_data: SetUpdate;
  /** How to apply list-like fields (tags, characters, notes). */
  operation_mode?: BulkOperationMode;
}
