/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * User-provided notes or context for the set.
 */
export type SetCreateNotes = string | null;
