/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SetCreateTitle } from './setCreateTitle';
import type { SetCreateSourceUrl } from './setCreateSourceUrl';
import type { SetCreateLocalPath } from './setCreateLocalPath';
import type { SetCreatePhash } from './setCreatePhash';
import type { SetCreateNotes } from './setCreateNotes';
import type { SetCreateTags } from './setCreateTags';
import type { ImageCreate } from './imageCreate';

export interface SetCreate {
  title?: SetCreateTitle;
  source_url?: SetCreateSourceUrl;
  local_path?: SetCreateLocalPath;
  phash?: SetCreatePhash;
  notes?: SetCreateNotes;
  tags?: SetCreateTags;
  creator_ids?: number[];
  images?: ImageCreate[];
}
