/**
 * @file
 * API model definition for setCreateNotes.
 * Generated automatically from the OpenAPI schema.
 * Represents data structures used in API requests and responses.
 */
/**
 * Defines the SetCreateNotes model.
 * Represents the notes payload when creating a set.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type SetCreateNotes = string | null;
