/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface SetCreate {
  title?: string | null;
  source_url?: string | null;
  local_path?: string | null;
  phash?: string | null;
  notes?: string | null;
  creator_ids?: number[];
}
