/**
 * @file
 * Defines the SetCreateLocalPath model.
 * Represents the local path payload when creating a set.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type SetCreateLocalPath = string | null;
