/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SetCreateTitle } from './setCreateTitle';
import type { SetCreateSourceUrl } from './setCreateSourceUrl';
import type { SetCreateLocalPath } from './setCreateLocalPath';
import type { SetCreatePhash } from './setCreatePhash';
import type { SetCreateNotes } from './setCreateNotes';
import type { ImageCreate } from './imageCreate';

export interface SetCreate {
  /** The display title of the set. */
  title?: SetCreateTitle;
  /** Original URL where the set was downloaded from. */
  source_url?: SetCreateSourceUrl;
  /** Local filesystem path where the set's files reside. */
  local_path?: SetCreateLocalPath;
  /** Perceptual hash representative of the set (usually the cover image). */
  phash?: SetCreatePhash;
  /** User-provided notes or context for the set. */
  notes?: SetCreateNotes;
  /** List of descriptive tag names for the set. */
  tags?: string[];
  /** List of character names for the set. */
  characters?: string[];
  /** List of creator IDs to associate with this set. */
  creator_ids?: number[];
  /** List of images to create and associate with this set. */
  images?: ImageCreate[];
}
