/**
 * API model definition for setImportLocalPath.
 * Generated automatically from the OpenAPI schema.
 * Represents data structures used in API requests and responses.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type SetImportLocalPath = string | null;
