/**
 * API model definition for setImport.
 * Generated automatically from the OpenAPI schema.
 * Represents data structures used in API requests and responses.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SetImportLocalPath } from './setImportLocalPath';
import type { ImageCreate } from './imageCreate';
import type { SetImportNotes } from './setImportNotes';

export interface SetImport {
  title: string;
  creator_names?: string[];
  local_path?: SetImportLocalPath;
  images?: ImageCreate[];
  notes?: SetImportNotes;
}
