/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface SetMerge {
  /** List of set IDs to merge. These sets will be deleted. */
  source_ids: number[];
  /** The ID of the set that will receive all images from the source sets. */
  target_id: number;
}
