/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { Set } from './set';

export interface SetPage {
  items: Set[];
  total: number;
  skip: number;
  limit: number;
}
