/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Perceptual hash representative of the set (usually the cover image).
 */
export type SetPhash = string | null;
