/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SettingDescription } from './settingDescription';

export interface Setting {
  value: string;
  description?: SettingDescription;
  key: string;
  updated_at: string;
}
