/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SettingDescription } from './settingDescription';

export interface Setting {
  /** The stringified value of the setting. */
  value: string;
  /** Human-readable explanation of what this setting controls. */
  description?: SettingDescription;
  /** Unique string key identifying the setting. */
  key: string;
  /** Timestamp when the setting was last modified. */
  updated_at: string;
}
