/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Human-readable explanation of what this setting controls.
 */
export type SettingDescription = string | null;
