/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SettingUpdateDescription } from './settingUpdateDescription';

export interface SettingUpdate {
  /** The new value for the setting. */
  value: string;
  /** Updated description. */
  description?: SettingUpdateDescription;
}
