/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SetUpdateTitle } from './setUpdateTitle';
import type { SetUpdateSourceUrl } from './setUpdateSourceUrl';
import type { SetUpdateLocalPath } from './setUpdateLocalPath';
import type { SetUpdatePhash } from './setUpdatePhash';
import type { SetUpdateNotes } from './setUpdateNotes';

export interface SetUpdate {
  title?: SetUpdateTitle;
  source_url?: SetUpdateSourceUrl;
  local_path?: SetUpdateLocalPath;
  phash?: SetUpdatePhash;
  notes?: SetUpdateNotes;
}
