/**
 * Type definition for updating a set's title in the API model.
 * Auto-generated by orval.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type SetUpdateTitle = string | null;
