/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Updated list of character names for this set.
 */
export type SetUpdateCharacters = string[] | null;
