/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Updated list of creator IDs for this set.
 */
export type SetUpdateCreatorIds = number[] | null;
