/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Comma-separated descriptive tags for the set.
 */
export type SetUpdateTags = string | null;
