/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SetUpdateTitle } from './setUpdateTitle';
import type { SetUpdateSourceUrl } from './setUpdateSourceUrl';
import type { SetUpdateLocalPath } from './setUpdateLocalPath';
import type { SetUpdatePhash } from './setUpdatePhash';
import type { SetUpdateNotes } from './setUpdateNotes';
import type { SetUpdateTags } from './setUpdateTags';
import type { SetUpdateCharacters } from './setUpdateCharacters';
import type { SetUpdateCreatorIds } from './setUpdateCreatorIds';

export interface SetUpdate {
  /** The display title of the set. */
  title?: SetUpdateTitle;
  /** Original URL where the set was downloaded from. */
  source_url?: SetUpdateSourceUrl;
  /** Local filesystem path where the set's files reside. */
  local_path?: SetUpdateLocalPath;
  /** Perceptual hash representative of the set (usually the cover image). */
  phash?: SetUpdatePhash;
  /** User-provided notes or context for the set. */
  notes?: SetUpdateNotes;
  /** Updated list of tag names for this set. */
  tags?: SetUpdateTags;
  /** Updated list of character names for this set. */
  characters?: SetUpdateCharacters;
  /** Updated list of creator IDs for this set. */
  creator_ids?: SetUpdateCreatorIds;
}
