/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface Tag {
  /** The name of the tag. */
  name: string;
  /** Unique database identifier for the tag. */
  id: number;
  /** Number of sets associated with this tag. */
  set_count?: number;
}
