/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Represents a tag, character, or franchise and its usage count.
 */
export interface TagCount {
  tag: string;
  type?: string;
  count: number;
}
