/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Represents a tag and the number of times it appears across all images and sets.
 */
export interface TagCount {
  tag: string;
  count: number;
}
