/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ThumbSize = typeof ThumbSize[keyof typeof ThumbSize];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ThumbSize = {
  sm: 'sm',
  md: 'md',
  lg: 'lg',
} as const;
