/**
 * @file
 * Type definition for OpenAPI validation error location items.
 * Auto-generated by orval.
 */
/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ValidationErrorLocItem = string | number;
